Initial solution
qiime2/q2cli pull request #322
Opened 2023-10-18 21:01 UTC by Oddant1

Closes #308 by expanding the `~` using `os.path.expanduser` allowing keyed de-facto collection elements to use a path starting with `~`. There might be a better place to use `os.path.expanduser`.

2023-11-27 22:55 UTC, gregcaporaso requested changes
@Oddant1, any reason not to include a new test for this case? Aside from that this looks good.

2023-11-28 20:04 UTC, Oddant1 commented
@gregcaporaso we would need to write to the user's home directory which I wanted to avoid doing. There may be some sort of work around for that, I didn't look too hard for one.

2023-11-30 15:12 UTC, gregcaporaso commented
That makes sense. How about confirming that the resulting path starts with `os.environ['HOME']`? (And I realize it's incredibly unlikely that this single line of code you're adding is buggy - I'm just aiming to prevent against a regression where someone removes this line because they assume Click is going to handle it.)

2023-11-30 17:10 UTC, Oddant1 commented
@gregcaporaso I just added a kinda real test, seemed like the thing to do. It wasn't difficult to work around writing to home which I figured it wouldn't be. Probably should have just done it already.

2023-11-30 20:00 UTC, gregcaporaso commented on q2cli/tests/test_cli.py
> +        yield
The try/yield/finally is a cool pattern - I don't think I've seen that before.

2023-11-30 20:02 UTC, gregcaporaso approved these changes
Looks good, thank you!

2023-11-30 20:03 UTC, merged